<?php

return [
    'inactive_after_minutes' => 15,
    'funny_names' => [
        'The Fast and the Curious',
        'Jurassic Bark',
        'The Lord of the Onion Rings',
        'The Sound of Moo-sic',
        'Raiders of the Lost Snark',
        'Pulp Friction',
        'The Breakfast Club Sandwich',
        'Indiana Jones and the Last Nap',
        'The Silence of the Clams',
        'Finding Emo',
        'Gone with the Windbreaker',
        'The Great Catsby',
        'The Muppetfather',
        'A Few Good Menus',
        'Star Warts',
        'Harry Potter and the Audacity',
        'The Wizard of Paws',
        'Mission: Impastable',
        'The Princess and the Popcorn',
        'Planet of the Grapes',
        'Kung Fu Pudding',
        'Crouching Tiger, Hidden Noodles',
        'Spirited Away With Snacks',
        'My Neighbor Tortoro',
        'Train to Busan-dwich',
        'Ramen Holiday',
        'The Wok-ing Dead',
        'Taco Story',
        'Guac to the Future',
        'Nacho Average Hero',
        'The Fajita Club',
        'La La Landline',
        'The Baguette Identity',
        'Amelie in a Hurry',
        'The Great British Bake-Off: The Movie',
        'Bond, James Bondi',
        'The Big Lebowski Pizza',
        'The Sardine King',
        'Mad Max: Ferry Road',
        'The Secret Life of Pies',
        'Harry Plotter',
        'The Matrix Reloaded My Phone',
        'Dial M for Miso',
        'The Good, the Bad, and the Crispy',
        'Brewce Almighty',
        'The Incredi-bowl',
        'Captain Ameri-cano',
        'Spider-Man: Far From Home Fries',
        'The Dark Knight Rises Dough',
        'Pirates of the Carob-bean',
        'The Breakfast Clubhouse',
        'Legally Blondies',
        'Shrekfast',
        'Frozen Yogurt',
        'The Lion King-sized',
        'Willy Wonka and the Chocolate Account',
        'Back to the Futon',
        'Meet the Forkers',
        'A Clockwork Orange Juice',
        'The Notebook of Doom',
        'The Hunger Games: Catching Fries',
        'The Sound of Muenster',
        'The Devil Wears Empanadas',
        'The Hummus Games',
        'The Shawshank Reduction',
        'No Country for Old Buns',
        'The Bourne Imitation Crab',
        'Eat Pray Love Handle',
        'The Gluten of the Rings',
    ],
    'avatars' => [
        ['id' => 'popcorn', 'label' => 'Popcorn', 'bg' => 'bg-amber-100', 'text' => 'text-amber-700', 'ring' => 'ring-amber-400/40'],
        ['id' => 'clapper', 'label' => 'Clapper', 'bg' => 'bg-slate-100', 'text' => 'text-slate-700', 'ring' => 'ring-slate-400/40'],
        ['id' => 'reel', 'label' => 'Reel', 'bg' => 'bg-stone-900', 'text' => 'text-white', 'ring' => 'ring-stone-500/40'],
        ['id' => 'ticket', 'label' => 'Ticket', 'bg' => 'bg-rose-100', 'text' => 'text-rose-700', 'ring' => 'ring-rose-400/40'],
        ['id' => 'projector', 'label' => 'Projector', 'bg' => 'bg-teal-100', 'text' => 'text-teal-700', 'ring' => 'ring-teal-400/40'],
        ['id' => 'star', 'label' => 'Star', 'bg' => 'bg-indigo-100', 'text' => 'text-indigo-700', 'ring' => 'ring-indigo-400/40'],
    ],
    'last_choice_messages' => [
        'up' => [
            'You greenlit it. The popcorn is cheering.',
            'Thumbs up. This one just made the shortlist.',
            'Bold yes. The couch leans in.',
            'Approved. The trailer voice booms: "Coming up!"',
            'You said yes. Snacks are on standby.',
            'That is a yes from you. The lobby applauds.',
            'Upvote vibes. This one could headline the night.',
            'You said yes. The remote agrees.',
            'Green light given. Cue the opening credits.',
            'A confident yes. The room hums with hype.',
            'Thumbs up. The popcorn does a victory lap.',
            'You are in. The studio is smiling.',
            'Approved. The couch cushions nod.',
            'A yes vote. The night gets brighter.',
            'Thumbs up. This one could be the main event.',
            'You are sold. The snacks are ready.',
            'Yes, and the crowd goes mild.',
            'Approved. The projector warms up.',
            'You chose yes. The hype meter ticks up.',
            'Up it goes. The vault door opens a crack.',
            'A yes vote. The group chat relaxes.',
            'Greenlit. The popcorn confetti cannon misfires.',
            'You are on board. The credits roll in your head.',
            'Thumbs up. This has weekend energy.',
            'Yes. The playlist shuffles with purpose.',
            'Confirmed. The blanket fort is interested.',
            'Approved. The sofa makes room.',
            'A strong yes. The soundtrack swells.',
            'Upvoted. The room leans forward.',
            'You went yes. The snacks high five.',
        ],
        'down' => [
            'You passed. The director is drafting an apology.',
            'Thumbs down. Back to the vault it goes.',
            'Hard pass. The credits never rolled.',
            'Denied. The popcorn mopes for a minute.',
            'Nope. The sequel just got canceled.',
            'Downvote. The couch stays skeptical.',
            'You said no. The trailer fades out.',
            'That is a pass. The room keeps searching.',
            'Rejected. The popcorn looks away.',
            'Thumbs down. The remote sighs.',
            'Nope. The studio goes back to the drawing board.',
            'You passed. The screen goes blank.',
            'Denied. The snacks are unconvinced.',
            'A no from you. The hype deflates.',
            'You said no. The vault door stays closed.',
            'Pass. The credits roll in silence.',
            'Downvote. The couch remains unmoved.',
            'No thanks. The director will understand.',
            'Nope. The night continues.',
            'Rejected. The popcorn is polite about it.',
            'Hard no. The trailer gets cut.',
            'Denied. The remote keeps searching.',
            'You passed. The spotlight shifts away.',
            'Down it goes. The lineup reshuffles.',
            'No vote. The hunt goes on.',
            'Pass. The room stays picky.',
            'Downvote. The snacks deserve better.',
            'No thanks. The hype meter resets.',
            'Nope. The couch declines.',
            'Rejected. The credits are on hold.',
        ],
    ],
];
