<?php

return [
    'funny_names' => [
        'The Fast and the Curious',
        'Jurassic Bark',
        'The Lord of the Onion Rings',
        'The Sound of Moo-sic',
        'Raiders of the Lost Snark',
        'Pulp Friction',
        'The Breakfast Club Sandwich',
        'Indiana Jones and the Last Nap',
        'The Silence of the Clams',
        'Finding Emo',
        'Gone with the Windbreaker',
        'The Great Catsby',
        'The Muppetfather',
        'A Few Good Menus',
        'Star Warts',
        'Harry Potter and the Audacity',
        'The Wizard of Paws',
        'Mission: Impastable',
        'The Princess and the Popcorn',
        'Planet of the Grapes',
        'Kung Fu Pudding',
        'Crouching Tiger, Hidden Noodles',
        'Spirited Away With Snacks',
        'My Neighbor Tortoro',
        'Train to Busan-dwich',
        'Ramen Holiday',
        'The Wok-ing Dead',
        'Taco Story',
        'Guac to the Future',
        'Nacho Average Hero',
        'The Fajita Club',
        'La La Landline',
        'The Baguette Identity',
        'Amelie in a Hurry',
        'The Great British Bake-Off: The Movie',
        'Bond, James Bondi',
        'The Big Lebowski Pizza',
        'The Sardine King',
        'Mad Max: Ferry Road',
        'The Secret Life of Pies',
        'Harry Plotter',
        'The Matrix Reloaded My Phone',
        'Dial M for Miso',
        'The Good, the Bad, and the Crispy',
        'Brewce Almighty',
        'The Incredi-bowl',
        'Captain Ameri-cano',
        'Spider-Man: Far From Home Fries',
        'The Dark Knight Rises Dough',
        'Pirates of the Carob-bean',
        'The Breakfast Clubhouse',
        'Legally Blondies',
        'Shrekfast',
        'Frozen Yogurt',
        'The Lion King-sized',
        'Willy Wonka and the Chocolate Account',
        'Back to the Futon',
        'Meet the Forkers',
        'A Clockwork Orange Juice',
        'The Notebook of Doom',
        'The Hunger Games: Catching Fries',
        'The Sound of Muenster',
        'The Devil Wears Empanadas',
        'The Hummus Games',
        'The Shawshank Reduction',
        'No Country for Old Buns',
        'The Bourne Imitation Crab',
        'Eat Pray Love Handle',
        'The Gluten of the Rings',
    ],
];
